# TO - DO :

# -- PRE-PROGRAMMING --
# visit source sites again - DONE
# choose 2-3 selection algorithms
# find + choose a good image processing library for python

# -- PROGRAMMING -- 
# choose photo(s) to upload - DONE
# read photo as text
# parse through photo, making selections/replacements/removals based on selection method
# execute through photo text in an iterative fashion, saving a copy of the photo text every so often
# then, save the series of images to disk
# if possible, turn series of images into a video and save THAT to disk instead/as well

# end of to - do.

import random

# welcome + file input
print("Welcome to the glitch generator.")
print("Please enter the name of the image to glitch, including the file extension (.jpg, .png, etc.).")
print("If you do not want to add an image to this repo, leave the input blank and press enter to use a preset.")
IMG_TO_GLITCH = input("")
if (IMG_TO_GLITCH == ""):
    IMG_TO_GLITCH = "real5.jpg"
    #IMG_TO_GLITCH = "wisdomteeth.png"

# open the binary data of the image
with open(IMG_TO_GLITCH, 'rb') as in_data:
    in_data = in_data.read() # reads in an object of class bytes
    ba = bytearray(in_data) # converts to a bytearray so we can modify the bytes directly. prints as hexadecimal (\x00)

# keep the header of the image safe
# if we don't, then it won't be able to convert back to an image
# jpg and jpeg headers end with \xff\xda
ba_length = len(ba)

#get SOS index
for i in range(ba_length):
    current_hex = ba[i]
    if i < ba_length - 1:
        next_hex = ba[i+1]
        if (current_hex == 0xff and next_hex == 0xda): ## \xff and \xda
            SOS_index = i + 2 + (ba[i+2] << 8) + ba[i+3]  # Start Of Scan index (where the image starts, after the header ends)
            print("SOS Index: " + str(SOS_index))
            print("Current and next hex: " + str(current_hex) + " " + str(next_hex))
            break #found end of header, now exit the loop


# cumulative glitch, using bit swapping
for frame in range(60): # range determines how many frames will be produced

    for c in range(5): # change 5 bytes each frame
        i = random.randint(SOS_index + (frame * 1000), ba_length - 3)

        # skip markers and stuffed bytes
        if ba[i] == 0xFF or (ba[i-1] == 0xFF and ba[i] == 0x00):
            continue

        # ^= is XOR
        # get the byte at ba[i], and use XOR with the byte generated by random.randint
        ba[i] ^= random.randint(1, 255)

    # make sure the last two bytes are 0xFF and 0xD9, or else the image will completely corrupt
    ba[-2] = 0xFF
    ba[-1] = 0xD9

    # save this frame (writing it as byte data again)
    with open(f"frame_{frame:03}.jpg", "wb") as out_data:
        out_data.write(ba)